# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2015

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  Archives: /archives
  Tags: /tags
  Categories: /categories
  Todo: /todo
  About: /about

# ===========================================
# Theme Settings
# ===========================================
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
color: Mint Green

# default page mode: default | archives
mode: default

toc: false

# jQuery fancybox
fancybox: false

# LaTeX support (via MathJax)
latex: false

copyright:
  enable: true
  # https://creativecommons.org/
  license: '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>'

reward:
  enable: false
  qrCode:
    wechat:
    alipay:

# ===========================================
# Social links Settings
# ===========================================
social:
  email: zeed.w.zhao@gmail.com
  stack-overflow:
  twitter:
  facebook:
  linkedin:
  google:
  github: https://github.com/zeed-w-beez
  weibo:
  zhihu:
  douban:
  pocket:
  tumblr:
  instagram:

# ===========================================
# Third Party Services Settings
# ===========================================

# LeanCloud
leancloud:
  app_id:
  app_key:

# Baidu Analytics
# baidu_analytics: 4df28318eb843c36d3db5661c05dafff
# Baidu Verification
# baidu_verification: dAGCCFnguk

# Google Analytics
# google_analytics: UA-109085701-1
# Google Verification
# google_verification: UbNkzWjJwlu0hdjVZnA_NkcGv6boCLQrnZ0hsjzJ7cM

# Disqus
disqus_shortname: zeed-w-beez

#Changyan
changyan:
  appid:
  appkey:

#LiveRe
livere_datauid:

# Gitalk
# Demo: https://gitalk.github.io
# https://github.com/gitalk/gitalk
gitalk:
  enable: false
  github_id: GitHub repo owner
  repo: GitHub repo
  client_id: GitHub Application Client ID
  client_secret: GitHub Application Client Secret
  admin_user: GitHub repo owner and collaborators, only these guys can initialize github issues
  distraction_free_mode: true # Facebook-like distraction free mode
  # Gitalk's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en, es-ES, fr, ru, zh-CN, zh-TW
  language:

# ===========================================
# Version
# ===========================================
version: 2.11.0
